# PyTorch

In [1]:
import torch
import numpy as np

In [2]:
x = torch.tensor(data=[2.0], requires_grad=True)

In [3]:
y = x ** 2

In [4]:
y.backward()

In [ ]:
x.grad
# tensor([4.])

tensor([4.])

## 0차원 텐서 생성

In [6]:
a = 1.0

In [ ]:
ts0 = torch.tensor(a)
# tensor(1.)

tensor(1.)

In [8]:
type(ts0)
# torch.Tensor
ts0.ndim
# 0
ts0.shape
# torch.Size([])
ts0.numel()
# 1
ts0.dtype
# torch.float32

torch.float32

## 1차원 텐서 생성

In [ ]:
li1 = [1, 2, 3]
# li1 = [1, 2.0, 3]
# li1 = [1, 2.0, '3']

ar1 = np.array(li1)
# array([1, 2, 3])
# array([1., 2., 3.])
# array(['1', '2.0', '3'], dtype='<U32')

ts1 = torch.tensor(li1)
# tensor([1, 2, 3])
# tensor([1., 2., 3.])
# 오류 - 파이토치 텐서는 수치형 원소만 가질 수 있음

In [11]:
type(ts1)
# torch.Tensor
ts1.ndim
# 1
ts1.shape
# torch.Size([3])
ts1.numel()
# 3
ts1.dtype
# torch.int64

torch.int64

## 1차원 텐서 원소의 자료형 변환

In [12]:
ts1.to(torch.float)
# tensor([1., 2., 3.])
ts1.to(torch.float).dtype
# torch.float32

torch.float32

In [ ]:
ts1 = ts1.float()
ts1.dtype
# torch.float32

In [14]:
ts1.to(torch.long)
# tensor([1, 2, 3])
ts1.to(torch.long).dtype
# torch.int64

torch.int64

In [ ]:
ts1 = ts1.long()
ts1.dtype
# torch.int64

torch.int64

## 2차원 텐서 생성

In [16]:
li2 = [[1, 3, 5], [7, 9, 11]]

In [ ]:
ts2 = torch.tensor(li2)
# tensor([[ 1,  3,  5],
#         [ 7,  9, 11]])

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [ ]:
type(ts2)
# torch.Tensor
ts2.ndim
# 2
ts2.shape
# torch.Size([2, 3])
ts2.numel()
# 6
ts2.dtype
# torch.int64

torch.int64

## 텐서의 재구조화

In [ ]:
ts1 = torch.arange(1, 12, 2)
# tensor([ 1,  3,  5,  7,  9, 11])

tensor([ 1,  3,  5,  7,  9, 11])

In [ ]:
ts2 = ts1.reshape(2, 3)
# tensor([[ 1,  3,  5],
#         [ 7,  9, 11]])

tensor([[ 1,  3,  5],
        [ 7,  9, 11]])

In [ ]:
ts2.flatten()
# tensor([ 1,  3,  5,  7,  9, 11])

tensor([ 1,  3,  5,  7,  9, 11])

## 무작위 값을 갖는 텐서 생성

In [28]:
torch.manual_seed(1)

In [ ]:
torch.rand(3, 2)
# tensor([[0.3398, 0.5239],
#         [0.7981, 0.7718],
#         [0.0112, 0.8100]])

tensor([[0.3398, 0.5239],
        [0.7981, 0.7718],
        [0.0112, 0.8100]])

In [ ]:
torch.randint(0, 5, (3, 2))
# tensor([[3, 1],
#         [2, 3],
#         [2, 3]])

tensor([[3, 1],
        [2, 3],
        [2, 3]])

In [35]:
torch.randn(1, 28, 28)

tensor([[[ 1.9906e-01,  4.5703e-02,  1.5296e-01, -4.7568e-01, -1.8821e+00,
          -7.7655e-01,  2.0242e+00, -8.6541e-02,  2.3571e+00, -1.0373e+00,
           1.5748e+00, -6.2985e-01,  2.4070e+00,  2.7857e-01,  2.4675e-01,
           1.1843e+00,  7.6260e-01,  4.4151e-01,  1.1651e+00,  2.0154e+00,
           2.1518e-01, -5.2419e-01, -1.8034e+00, -1.3083e+00,  1.5392e+00,
          -8.6959e-01, -3.3312e+00, -7.4787e-01],
         [ 1.1173e+00,  2.9814e-01,  1.0989e-01, -6.4634e-01, -2.1061e-01,
          -7.5475e-03,  1.6734e+00,  1.0343e-02,  9.8371e-01,  8.7929e-01,
          -1.4504e+00, -1.1802e+00, -4.6102e-01, -5.6008e-01,  3.9558e-01,
          -9.8228e-01,  1.3264e+00,  8.5472e-01, -2.8052e-01,  7.0002e-01,
          -1.4344e+00, -5.0081e-01,  1.7163e-01, -1.5999e-01, -5.0467e-01,
          -1.4746e+00, -3.4158e-01, -3.0026e-01],
         [-1.0483e+00, -4.7088e-01,  2.9114e-01,  1.9907e+00, -9.2470e-01,
          -9.3010e-01,  1.4301e+00,  4.2077e-01,  1.3851e+00, -8.1385e-01,


## 가상의 이미지 데이터 생성

In [36]:
gray_img = torch.randn(1, 28, 28)

In [37]:
color_img = torch.randn(3, 32, 32)

In [42]:
img_batch = torch.randn(128, 3, 32, 32)

- flatten 메서드는 전체 원소를 1차원으로 평탄화
    - 따라서 배치 크기를 고려하지 못함
- 배치 크기를 유지한 상태로 평탄화하려면 reshape 메서드 사용

In [ ]:
img_batch.shape
# torch.Size([128, 3, 32, 32])
img_batch.flatten().shape
# torch.Size([393216])
img_batch.reshape(128, -1).shape
# torch.Size([128, 3072])

torch.Size([393216])

## 브로드캐스팅

In [ ]:
ts1 = torch.tensor([0, 1, 2])
ts1 + 1
# tensor([1, 2, 3])

tensor([1, 2, 3])

In [ ]:
ts2 = ts1.reshape(-1, 1)
ts2 * 2
# tensor([[0],
#         [2],
#         [4]])

tensor([[0],
        [2],
        [4]])

## 차원 추가 및 제거

- squeeze 메서드는 원소 개수가 1인 축만 제거할 수 있음
    - dim 지정 생략 시 원소 개수가 1인 축을 모두 제거

In [ ]:
ts1.unsqueeze(dim=0)
# tensor([[0, 1, 2]])
ts1.unsqueeze(dim=0).shape
# torch.Size([1, 3])

torch.Size([1, 3])

In [ ]:
ts2.squeeze(dim=1)
# tensor([0, 1, 2])
ts2.squeeze(dim=1).shape
# torch.Size([3])

torch.Size([3])

## 텐서의 결합

In [ ]:
x1 = torch.tensor([0, 1, 2])
x2 = torch.tensor([3, 4, 5])

torch.stack(tensors=[x1, x2], dim=0)
# tensor([[0, 1, 2],
#         [3, 4, 5]])
torch.stack(tensors=[x1, x2], dim=1)
# tensor([[0, 3],
#         [1, 4],
#         [2, 5]])

torch.Size([2, 3])

In [ ]:
gray_img_1 = torch.randn(1, 28, 28)
gray_img_2 = torch.randn(1, 28, 28)

img_batch_1 = torch.stack(tensors=[gray_img_1, gray_img_2], dim=0)
img_batch_1.shape
# torch.Size([2, 1, 28, 28])

torch.Size([2, 1, 28, 28])

## 텐서 입력 형태 변환

In [ ]:
ts1
# tensor([0, 1, 2])

tensor([0, 1, 2])

In [ ]:
ts1 = ts1.unsqueeze(dim=0).unsqueeze(dim=0)
ts1.shape
# torch.Size([1, 1, 3])

torch.Size([1, 1, 3])

- permute 메서드는 차원 축을 일괄로 바꾸는 기능이 있음
    - np.transpose() 가 동일한 기능을 수행

In [ ]:
ts1.permute(0, 2, 1).shape
# torch.Size([1, 3, 1])
ts1.permute(2, 0, 1).shape
# torch.Size([3, 1, 1])

torch.Size([1, 3, 1])

- transpose 메서드는 2개의 차원을 서로 맞바꾸는 기능이 있음
    - np.swapaxes() 가 동일한 기능을 수행

In [ ]:
ts1.transpose(1, 2).shape
# torch.Size([1, 3, 1])
ts1.transpose(0, 2).shape
# torch.Size([3, 1, 1])

torch.Size([1, 3, 1])