## PyTorch Tensor 연습문제

이 노트북은 딥러닝 프레임워크(PyTorch)를 사용하기 위한 **텐서 연습문제**로 구성되어 있습니다.

- 아주 쉬운 문제부터 시작하여 점점 난이도가 올라갑니다.
- 각 문제는 **마크다운 설명 -> 코드 셀** 순서로 구성되어 있습니다.

### 필요한 모듈 임포트

In [1]:
# 필요한 모듈을 임포트합니다.
import torch

In [2]:
# torch 버전을 확인합니다.
# [참고] 이 노트북은 torch 2.2.2 버전에서 작성되었습니다.
torch.__version__

'2.2.2'

### 연습 문제 1: 1차원 벡터

다음 텐서 `ts1`을 생성하고, 관련 정보를 확인합니다.

In [3]:
# 1차원 텐서 ts1을 생성합니다.
ts1 = torch.tensor(data = [1, 2, 3, 4, 5, 6])

In [4]:
# ts1을 확인합니다.
ts1

tensor([1, 2, 3, 4, 5, 6])

In [5]:
# ts1의 차원을 확인하세요.
ts1.ndim

1

In [6]:
# ts1의 형태를 확인하세요.
ts1.shape

torch.Size([6])

In [8]:
# ts1의 원소 개수를 확인하세요.
ts1.numel()

6

In [9]:
# ts1의 원소 자료형을 확인하세요.
ts1.dtype

torch.int64

In [11]:
# ts1의 원소 자료형을 32비트 실수로 변환한 결과를 확인하세요.
# [주의] 위 코드 실행 결과를 ts1에 재할당하지 않습니다.
ts1.float().dtype

torch.float32

In [12]:
# ts1의 첫 번째 원소를 선택하세요.(인덱싱)
ts1[0]

tensor(1)

In [13]:
# ts1의 마지막 원소를 선택하세요.(인덱싱)
ts1[-1]

tensor(6)

In [16]:
# ts1의 가운데 2개 원소를 선택하세요.(슬라이싱)
print(ts1)
ts1[2:4]

tensor([1, 2, 3, 4, 5, 6])


tensor([3, 4])

In [21]:
# ts1에서 홀수인 원소만 선택하세요.(팬시 인덱싱)
ts1[[0, 2, 4]]

tensor([1, 3, 5])

In [19]:
# ts1에서 짝수인 원소만 선택하세요.(불리언 인덱싱)
mask = ts1 % 2 == 0
ts1[mask]

tensor([2, 4, 6])

In [22]:
# ts1을 3행 2열인 2차원 텐서로 변환한 결과를 확인하세요.
ts1.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

### 연습 문제 2: 2차원 행렬

다음 텐서 `ts2`를 생성하고, 관련 정보를 확인합니다.

In [23]:
# 시드를 고정합니다.
torch.manual_seed(seed = 1)

In [24]:
# 2차원 텐서 ts2를 생성합니다.
ts2 = torch.randn(size = (4, 5))

In [25]:
# ts2를 확인합니다.
ts2

tensor([[-1.5256, -0.7502, -0.6540, -1.6095,  0.8657],
        [ 0.2444, -0.6629,  0.8073,  0.4391,  1.1712],
        [ 1.7674, -0.0954,  0.0612, -0.6177, -0.7981],
        [-0.1316, -0.7984,  0.3357,  0.2753,  1.7163]])

In [26]:
# ts2의 차원을 확인하세요.
ts2.ndim

2

In [27]:
# ts2의 형태를 확인하세요.
ts2.shape

torch.Size([4, 5])

In [28]:
# ts2의 원소 자료형을 확인하세요.
ts2.dtype

torch.float32

In [29]:
# ts2의 원소 자료형을 64비트 정수로 변환한 결과를 확인하세요.
# [주의] 위 코드 실행 결과를 ts2에 재할당하지 않습니다.
ts2.long().dtype

torch.int64

In [30]:
# ts2의 첫 번째 행, 첫 번째 열의 성분을 선택하세요.
ts2[0, 0]

tensor(-1.5256)

In [31]:
# ts2의 마지막 행, 마지막 열의 성분을 선택하세요.
ts2[-1, -1]

tensor(1.7163)

In [33]:
# ts2의 첫 번째 열 벡터를 선택하세요.
ts2[:, 0]

tensor([-1.5256,  0.2444,  1.7674, -0.1316])

In [34]:
# ts2의 세 번째 행 벡터를 선택하세요.
ts2[2, :]

tensor([ 1.7674, -0.0954,  0.0612, -0.6177, -0.7981])

In [37]:
# ts2를 5행 4열인 2차원 텐서로 변환한 결과를 확인하세요.
ts2.reshape(5, 4)

tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
        [ 0.8657,  0.2444, -0.6629,  0.8073],
        [ 0.4391,  1.1712,  1.7674, -0.0954],
        [ 0.0612, -0.6177, -0.7981, -0.1316],
        [-0.7984,  0.3357,  0.2753,  1.7163]])

In [38]:
# ts2를 1차원 텐서로 변환한 결과를 확인하세요.
ts2.flatten()

tensor([-1.5256, -0.7502, -0.6540, -1.6095,  0.8657,  0.2444, -0.6629,  0.8073,
         0.4391,  1.1712,  1.7674, -0.0954,  0.0612, -0.6177, -0.7981, -0.1316,
        -0.7984,  0.3357,  0.2753,  1.7163])

### 연습 문제 3: 배치 차원 추가 및 제거

한 장의 흑백 이미지가 (높이, 너비) = (28, 28) 형태로 들어있다고 가정합니다.

In [39]:
# 시드를 고정합니다.
torch.manual_seed(seed = 1)

In [40]:
# 흑백 이미지 텐서를 생성합니다.
img = torch.randn(size = (28, 28))

In [41]:
# img를 확인합니다.
img

tensor([[-1.5256e+00, -7.5023e-01, -6.5398e-01, -1.6095e+00, -1.0017e-01,
         -6.0919e-01, -9.7977e-01, -1.6091e+00, -7.1214e-01,  3.0372e-01,
         -7.7731e-01, -2.5146e-01, -2.2227e-01,  1.6871e+00,  2.2843e-01,
          4.6764e-01, -6.9697e-01, -1.1608e+00,  6.9954e-01,  1.9908e-01,
          8.6569e-01,  2.4440e-01, -6.6291e-01,  8.0731e-01,  1.1017e+00,
         -1.7594e-01, -2.2456e+00, -1.4465e+00],
        [ 6.1155e-02, -6.1774e-01, -7.9807e-01, -1.3162e-01,  1.8793e+00,
         -7.2132e-02,  1.5777e-01, -7.7345e-01,  1.9906e-01,  4.5703e-02,
          1.5296e-01, -4.7568e-01, -1.1102e-01,  2.9274e-01, -1.5785e-01,
         -2.8787e-02,  2.3571e+00, -1.0373e+00,  1.5748e+00, -6.2985e-01,
         -9.2739e-01,  5.4514e-01,  6.6280e-02, -4.3704e-01,  7.6260e-01,
          4.4151e-01,  1.1651e+00,  2.0154e+00],
        [ 1.3741e-01,  9.3864e-01, -1.8600e-01, -6.4464e-01,  1.5392e+00,
         -8.6959e-01, -3.3312e+00, -7.4787e-01, -2.5502e-02, -1.0233e+00,
         -5.96

In [42]:
# img에 채널 차원을 추가하여 (채널, 높이, 너비) = (1, 28, 28) 형태인 img_a를 생성하세요.
img_a = img.unsqueeze(dim=0)

In [43]:
# img_a의 형태를 확인하세요.
img_a.shape

torch.Size([1, 28, 28])

In [44]:
# img_a에 배치 차원을 추가하여 (배치, 채널, 높이, 너비) = (1, 1, 28, 28) 형태인 img_b를 생성하세요.
img_b = img_a.unsqueeze(dim=0)

In [45]:
# img_b의 형태를 확인하세요.
img_b.shape

torch.Size([1, 1, 28, 28])

In [46]:
# img_b에서 배치 차원을 제거하여 (채널, 높이, 너비) = (1, 28, 28) 형태인 img_c를 생성하세요.
img_c = img_b.squeeze(dim=0)

In [47]:
# img_c의 형태를 확인하세요.
img_c.shape

torch.Size([1, 28, 28])

### 연습 문제 4: 완전연결층 입력을 위한 평탄화

다음 텐서는 32장의 컬러 이미지(3, 32, 32)로 이루어진 미니배치입니다.

In [48]:
# 시드를 고정합니다.
torch.manual_seed(seed = 1)

In [49]:
# 미니배치를 생성합니다.
# [참고] 텐서 x의 형태를 (배치, 채널, 높이, 너비)이라고 가정합니다.
x = torch.randn(size = (32, 3, 32, 32))

In [50]:
# x를 확인합니다.
x

tensor([[[[-1.5256e+00, -7.5023e-01, -6.5398e-01,  ..., -6.1774e-01,
           -7.9807e-01, -1.3162e-01],
          [ 1.8793e+00, -7.2132e-02,  1.5777e-01,  ..., -8.6959e-01,
           -3.3312e+00, -7.4787e-01],
          [-2.5502e-02, -1.0233e+00, -5.9619e-01,  ..., -4.7088e-01,
            2.9114e-01,  1.9907e+00],
          ...,
          [-1.1414e+00, -1.9074e+00, -1.1947e+00,  ..., -1.2189e+00,
           -1.7901e+00,  6.9978e-01],
          [ 9.9596e-01, -2.1980e-01,  1.3966e-01,  ...,  1.6160e+00,
           -4.7004e-01, -6.5659e-01],
          [-1.5116e+00,  1.9068e-01,  2.0442e-01,  ...,  1.6362e-01,
            8.4142e-01,  1.0562e+00]],

         [[ 8.9364e-01, -1.0561e+00, -1.7766e-01,  ..., -3.3239e-01,
           -1.7864e+00, -1.5912e-01],
          [ 1.4047e+00, -6.1112e-01, -4.7914e-01,  ..., -1.4921e+00,
            5.4320e-01,  5.2151e-01],
          [ 7.4374e-01, -2.0438e+00, -1.2827e+00,  ...,  1.0513e-01,
            1.9856e-02, -6.8022e-01],
          ...,
     

In [51]:
# x를 완전연결층에 입력할 수 있도록 (32, 3*32*32) 형태인 x_flat을 생성하세요.
x_flat = x.reshape(32, -1)

In [52]:
# x_flat의 형태를 확인하세요.
x_flat.shape

torch.Size([32, 3072])

### 연습 문제 5: 차원 순서 바꾸기(NHWC -> NCHW)

어떤 라이브러리에서 이미지를 (배치, 높이, 너비, 채널) 구조로 반환한다고 가정합니다.

In [53]:
# 시드를 고정합니다.
torch.manual_seed(seed = 1)

In [54]:
# 미니배치를 생성합니다.
# [참고] 텐서 x의 형태를 (배치, 높이, 너비, 채널)이라고 가정합니다.
x = torch.randn(size = (32, 32, 32, 3))

In [55]:
# x를 확인합니다.
x

tensor([[[[-1.5256e+00, -7.5023e-01, -6.5398e-01],
          [-1.6095e+00, -1.0017e-01, -6.0919e-01],
          [-9.7977e-01, -1.6091e+00, -7.1214e-01],
          ...,
          [-1.5999e-01,  2.5463e-01, -5.0196e-01],
          [-1.0412e+00,  7.3227e-01, -1.0483e+00],
          [-4.7088e-01,  2.9114e-01,  1.9907e+00]],

         [[ 6.6145e-01,  1.1899e+00,  8.1653e-01],
          [-9.1352e-01,  1.3851e+00, -8.1385e-01],
          [-9.2758e-01,  1.1120e+00,  1.3352e+00],
          ...,
          [-3.5822e-01,  1.7223e+00, -3.0358e-01],
          [ 2.3887e-01,  1.3440e+00,  1.0323e-01],
          [ 1.1004e+00, -3.4168e-01,  9.4734e-01]],

         [[-5.6852e-01,  8.3760e-01,  1.7837e+00],
          [-1.9542e-01,  5.1492e-01, -1.8475e+00],
          [-2.9167e+00, -5.6733e-01, -5.4128e-01],
          ...,
          [ 1.0644e+00,  8.3403e-01, -1.9162e+00],
          [-3.4203e-01, -6.6049e-01,  3.1509e-01],
          [ 1.1423e+00,  3.0551e-01, -5.7888e-01]],

         ...,

         [[ 1.88

In [56]:
# x를 PyTorch CNN 입력 형태인 (N, C, H, W)로 변환한 결과를 확인하세요.(permute 메서드 사용)
x.permute(0, 3, 1, 2)

tensor([[[[-1.5256e+00, -1.6095e+00, -9.7977e-01,  ..., -1.5999e-01,
           -1.0412e+00, -4.7088e-01],
          [ 6.6145e-01, -9.1352e-01, -9.2758e-01,  ..., -3.5822e-01,
            2.3887e-01,  1.1004e+00],
          [-5.6852e-01, -1.9542e-01, -2.9167e+00,  ...,  1.0644e+00,
           -3.4203e-01,  1.1423e+00],
          ...,
          [ 1.8889e+00, -3.0566e-03, -6.2695e-01,  ..., -2.2303e-01,
            1.5968e-02,  6.4465e-01],
          [ 1.9706e+00,  4.9625e-02,  5.2096e-01,  ..., -3.4559e-01,
            1.2202e-01,  1.0775e+00],
          [ 5.8250e-01, -1.2741e+00, -9.3213e-01,  ...,  2.6296e-02,
           -2.4616e+00,  1.2993e+00]],

         [[-7.5023e-01, -1.0017e-01, -1.6091e+00,  ...,  2.5463e-01,
            7.3227e-01,  2.9114e-01],
          [ 1.1899e+00,  1.3851e+00,  1.1120e+00,  ...,  1.7223e+00,
            1.3440e+00, -3.4168e-01],
          [ 8.3760e-01,  5.1492e-01, -5.6733e-01,  ...,  8.3403e-01,
           -6.6049e-01,  3.0551e-01],
          ...,
     

In [ ]:
# x를 PyTorch CNN 입력 형태인 (N, C, H, W)로 변환한 결과를 확인하세요.(transpose 메서드 사용)
x.transpose(1, 2).transpose(1, 3)

tensor([[[[-1.5256e+00, -1.6095e+00, -9.7977e-01,  ..., -1.5999e-01,
           -1.0412e+00, -4.7088e-01],
          [ 6.6145e-01, -9.1352e-01, -9.2758e-01,  ..., -3.5822e-01,
            2.3887e-01,  1.1004e+00],
          [-5.6852e-01, -1.9542e-01, -2.9167e+00,  ...,  1.0644e+00,
           -3.4203e-01,  1.1423e+00],
          ...,
          [ 1.8889e+00, -3.0566e-03, -6.2695e-01,  ..., -2.2303e-01,
            1.5968e-02,  6.4465e-01],
          [ 1.9706e+00,  4.9625e-02,  5.2096e-01,  ..., -3.4559e-01,
            1.2202e-01,  1.0775e+00],
          [ 5.8250e-01, -1.2741e+00, -9.3213e-01,  ...,  2.6296e-02,
           -2.4616e+00,  1.2993e+00]],

         [[-7.5023e-01, -1.0017e-01, -1.6091e+00,  ...,  2.5463e-01,
            7.3227e-01,  2.9114e-01],
          [ 1.1899e+00,  1.3851e+00,  1.1120e+00,  ...,  1.7223e+00,
            1.3440e+00, -3.4168e-01],
          [ 8.3760e-01,  5.1492e-01, -5.6733e-01,  ...,  8.3403e-01,
           -6.6049e-01,  3.0551e-01],
          ...,
     

## End of Document